security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        # Dev firewall context
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Default main firewall context
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserLoginAuthenticator
            
            json_login:
                check_path:    /api/login
                username_path: security.credentials.login
                password_path: security.credentials.password


            logout:
                path: app_logout
                # Redirection après logout
                target: app.home

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # pour switcher mettre à la fin de l'url à tester: ?_switch_user=mailatester@mail.fr
            # pour mettre fin au switch ajouter à la fin de l'url en test: ?_switch_user=_exit
            switch_user: true

            # ^ début de l'url
            # /back pour limiter au backoffice
            # [^/] tout ce qui n'est pas un / (=> le nom du modèle peut importe le model)
            # + 1 ou plusieurs fois le caractère précédente
            # / le slash
            # \d+ un nombre
            # $ fin de l'url

    access_control:
          - { path: ^/api/login, roles: PUBLIC_ACCESS }
          - { path: ^/api/users/register, roles: PUBLIC_ACCESS }
          - { path: ^/api/users$, roles: PUBLIC_ACCESS }
          - { path: ^/api/users/delete/\d+, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        # ROLE_ADMIN: [ROLE_MANAGER, ROLE_ALLOWED_TO_SWITCH]
        # ROLE_MANAGER: ROLE_USER
        # ROLE_USER: ROLE_TEST

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
